[package]
name = "openh264"
version = "0.1.0"
authors = ["Kornel LesinÌski <kornel@geekhood.net>"]
categories = [ "multimedia::video", "multimedia::encoding", "api-bindings" ]

[dependencies]
openh264-sys = { path = "sys" }

[lib]
doctest = false
