[package]
authors = ["Kornel LesinÌski <kornel@geekhood.net>"]
build = "src/build.rs"
license = "BSD-2-Clause"
name = "openh264-sys"
version = "0.1.0"

[build-dependencies]
pkg-config = "0.3.9"

[lib]
name = "openh264_sys"
doctest = false
